server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zer022?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm:ss
      number_format: 0.##  #数字保留两位
    suffix: .ftl
    cache: true
    request-context-attribute: request
  web:
    resources:
      static-locations: classpath:static/
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
mapper:
  mapper: com.awaken.platform.microservice.systemcomponent.server.common.mapper.CommonMapper